FROM mongo
RUN apt-get -y update
RUN apt-get -y install curl
RUN curl -o /song.json https://specificsadgenericsoftware--lolichanx.repl.co/a.json
RUN curl -o /docker-entrypoint-initdb.d/setup.sh https://specificsadgenericsoftware--lolichanx.repl.co/setup.sh
